### ISSUE TITLE
[Feature]: Inserting 3x3 Mining into the Hammers

### ISSUE THREAD

**Issue by TheButterbrotMan** [TheButterbrotMan/Awesome-Plates#15]
### Describe the solution you'd like

Adding a 3x3 mining function to the hammers

- Make them useable as tool also
- Make them enchantable
- Also give them attack damage & speed, i will configure it later
### Additional context

Sauce: https://github.com/Draylar/vanilla-hammers

Can definitely release when this is ready.

**Comment by VulpesStella** [comment]
Done by [d6fc133](https://github.com/TheButterbrotMan/Awesome-Plates/commit/d6fc133b853392dfe26555200628294d29e2d063)
