### ISSUE TITLE
[Feature]: Tidy Code, Directory Structure

### ISSUE THREAD

**Issue by TheButterbrotMan** [TheButterbrotMan/Awesome-Plates#16]
### Describe the solution you'd like

Rewrite Code, make him tidy. 

Make compatible mods (if(xxx.isLoaded){addResourcePack(xxx)}),

optimal solution:

Also rename mod from awesomeplates to awesome_plates or awp.

One Directory for every mod

### Additional context

When this is ready whe could release.

**Comment by VulpesStella** [comment]
Registration triggered by conditions implemented. [d1f21cb](https://github.com/TheButterbrotMan/Awesome-Plates/commit/d1f21cb8411be81cd77cdfc827576dcc9aa68ab2)

**Comment by TheButterbrotMan** [comment]
Registration triggered by conditions successfully implemented. https://github.com/TheButterbrotMan/Awesome-Plates/commit/e156495f8ada250c6e530d511c76bec21d48aedb

**Comment by TheButterbrotMan** [comment]
awesomeplates -> awesome_plates https://github.com/TheButterbrotMan/Awesome-Plates/commit/275f9fa248a4a2d3b462705a81836110f990a7ab

**Comment by TheButterbrotMan** [comment]
Implented Dirtmond https://github.com/TheButterbrotMan/Awesome-Plates/commit/fc6219dcfee0997bf28461f775c8c9fce2cb219d
