### ISSUE TITLE
[Bug]: Snow in unusual places

### ISSUE THREAD

**Issue by wildficus** [TheButterbrotMan/Awesome-Plates#20]
### What happened?

Snow blocks(AND ICE, if there is water there) spawn sometimes in places i do not expect to see them(deserts, jungles, random non snowy biomes), right when creating a new world. This causes a lot of lag, as they despawn and hurt performance when looking at such chunks with these snow blocks on them. It seems that multiple chunks get this effect. I do not know if its a feature from some seasons mod or something else however the lag is pretty disruptive

This happened in every new world i have created thus far (7 to be exact).
Example provided:
![image](https://user-images.githubusercontent.com/61603266/152177041-227a41d1-ab3a-4c15-8788-a99c13b85170.png)

### Version

1.0

### Provide the log

There is no logs to provide unfortunately.

**Comment by wildficus** [comment]
Sorry wrong github, very very sorry. Dunno how to delete, else i would.

**Comment by TheButterbrotMan** [comment]
No problem haha
