### ISSUE TITLE
[Feature]: Output when "if" mod is detected 

### ISSUE THREAD

**Issue by TheButterbrotMan** [TheButterbrotMan/Awesome-Plates#22]
### Describe the solution you'd like

A output in the log when a "if" mod got detected, could be really usefull adressing bugs in the future.

Example:

A compatibility patch for Dirtmond is getting loaded.

**Comment by VulpesStella** [comment]
[92fb864](https://github.com/TheButterbrotMan/Awesome-Plates/commit/92fb864c73c3df4332d7c06f17d7b46031dfae63) implemented.
