### ISSUE TITLE
[Feature]: make it more evil

### ISSUE THREAD

**Issue by kreezxil** [TheButterbrotMan/Awesome-Plates#29]
### Is your feature request related to a problem? Please describe.

not a problem, just make it more harder, lol.

saw a way you can add to the headache. all the items you can make plates of, remove the standard block recipe thereof and require 16 of your plates to make the compressed normal vanilla block version. then add furnace or blast furnace recipes to melt those back into their base values of ingot or diamond.

### Describe the solution you'd like

saw a way you can add to the headache. all the items you can make plates of, remove the standard block recipe thereof and require 16 of your plates to make the compressed normal vanilla block version. then add furnace or blast furnace recipes to melt those back into their base values of ingot or diamond.

**Comment by TheButterbrotMan** [comment]
I did think about it and had some idea! :)

9 Plates -> 1 Block -> 1 Block + Hammer -> 9 Plates -> (Furnace) 1 Plate -> 1 Ingot

What do you think?

**Comment by kreezxil** [comment]
so the vibration of the plates caused by the hammer hitting them as a block
separates them? If so, perhaps

(8 plates + slime ball) == 1 block
(1 block + hammer) == 8 Plates
1 plate in a furnace = 1 ingot

the ->'s were confusing.

**Comment by kreezxil** [comment]
slime ball and clay ball should both be allowed to bind the 8 plates
together.

**Comment by TheButterbrotMan** [comment]
That sounds good!

**Comment by kreezxil** [comment]
Let me know when that's implemented, It'll be a blast to implement in one
of my packs.

**Comment by TheButterbrotMan** [comment]
I'll do! :) Maybe i achieve it in the week. But probably I first have time at the weekend.

**Comment by kreezxil** [comment]
Sounds good!

**Comment by TheButterbrotMan** [comment]
It seems to be impossible to give a furnace multiple "count" outputs (=4 Ingots from 1 Plate), so a maximum of one ingot can be given back from one plate.

https://github.com/TheButterbrotMan/Awesome-Plates/commit/257738ee2043be5b9fc8108752fdb62223c83646

I will do some code tidying later, then i upload the new version. I will also add the new recipes later to the wiki, and probably remove the horse armors.

**Comment by TheButterbrotMan** [comment]
As you can see here: https://github.com/TheButterbrotMan/Awesome-Plates/blob/257738ee2043be5b9fc8108752fdb62223c83646/src/main/resources/data/awesome_plates/tags/items/balls.json#L6

I also added the ability to craft the compressed blocks with honey.

**Comment by TheButterbrotMan** [comment]
Will be soon on curseforge! :)

**Comment by kreezxil** [comment]
Awesome, thanks!
