### ISSUE TITLE
[Feature]: Create mod compatibility

### ISSUE THREAD

**Issue by Gantros** [TheButterbrotMan/Awesome-Plates#30]
### Is your feature request related to a problem? Please describe.

Not a problem, per se, but I would like to see compatibility with Create so that you can use the metal plates from that mod instead of using the Hammer from yours.

### Describe the solution you'd like

See above.

**Comment by TheButterbrotMan** [comment]
Please add a link for the mod.

**Comment by Gantros** [comment]
> Please add an link for the mod.

https://www.curseforge.com/minecraft/mc-mods/create

**Comment by VulpesStella** [comment]
> > Please add an link for the mod.
> 
> https://www.curseforge.com/minecraft/mc-mods/create

Create hasn't released their fabric port yet...
But thanks for your suggestion, will definitely add compatibility when we have this mod ported to Forge :D
